# -*- coding: utf-8 -*-
"""Задание_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WV0cxsFhnSswqlS5cHTJqtf2DWBRNP4H
"""

!pip install numpy==1.22.0  # какие-то проблемы с зависимостямя
!pip install geopandas mapclassify  # mapclassify для визуализации
!pip install geopandas
!pip install keplergl  # для визуализации
!pip install osmnx  # устанавливаем модуль osmnx

import pandas as pd
import geopandas as gpd
import osmnx as ox
# для визуализации данных
from keplergl import KeplerGl
# для отображение в colab
from google.colab import output
output.enable_custom_widget_manager()

def get_google_drive_download_url(url: str) -> str:
    """
    Функция возвращает ссылку для скачивания с google drive.
    """
    drive_id = url.split("/")[5]
    return f"https://drive.google.com/uc?export=download&id={drive_id}"

# ссылки на файлы к данным
buildings_url = 'https://drive.google.com/file/d/1mPCmMWWQCHtFL9DscTKrQh3X9h_REBMS/view?usp=share_link'
adresses_url = 'https://drive.google.com/file/d/1AsREpC-w_4TPoCzB25-6OL6wGVAsmp7-/view?usp=share_link'

# загрузка данных
buildings = gpd.read_file(get_google_drive_download_url(buildings_url))
adresses = gpd.read_file(get_google_drive_download_url(adresses_url))

# датафрем со зданиями
buildings.head()

# датафрем с адресами в виде точек
adresses.head()

# визуализируем здания
buildings.explore()

# визуализируем точки с адресами
adresses.explore()

# Получим датафрем с геокодированием, путем объединения датафреймов
geocode_buildings = buildings.sjoin(adresses, how="left")
geocode_buildings.head()

# Отобразим полученные датафрейм с геокодированием
geocode_buildings.explore()

# разобьем датафрем на две части по наличию адреса
geocode_buildings_without_adress = geocode_buildings.loc[geocode_buildings['addr:street'].isna(), :] # здания без адреса 
geocode_buildings_with_adress = geocode_buildings.loc[geocode_buildings['addr:street'].notna(), :] # здания c адресом

# визуализируем в кеплер
map = KeplerGl(height=700)
map.add_data(data=geocode_buildings_without_adress.copy(), name='здания без адреса')
map.add_data(data=geocode_buildings_with_adress.copy(), name='здания с адресом')
map

